### PR TITLE
fix some  some still broken

### PR DESCRIPTION
**Pull request by iacore**

### CODE REVIEW

**Comment by iacore** [comment]
oops. wrong direction

**Comment by donpdonp** [comment]
what version of zig does this build with?

```
switched to branch 'iacore'
donp@carbon [git:iacore] zootdeck $ make
zig build
/home/donp/projects/zootdeck/build.zig:3:20: error: root struct of file 'std' has no member named 'build'
const Builder = std.build.Builder;
                ~~~^~~~~~
$ zig version
0.13.0
```

**Comment by iacore** [comment]
> what version of zig does this build with?

This doesn't build with any version of Zig; I was working with Zig 0.11.0.

**Comment by donpdonp** [comment]
okay well master is up to date with what ive been doing to try to get it to compile again under 0.13. Ive got it down to one statement in main.zig's main() function where the compiler complains about an unspecified format for printing an exception, but im stuck as to how to fix it. it might be a compiler problem.
